services:
  - type: web
    name: jahani-backend
    runtime: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "app.settings"
      - key: ALLOWED_HOSTS
        value: "jahani-mart-backend.onrender.com,jahani-mart.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://jahani-mart.onrender.com"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_lbh86WCGBeDt@ep-hidden-bread-a1y4ehiu-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
      - key: CLOUDINARY_CLOUD_NAME
        value: "ddoibtvxo"
      - key: CLOUDINARY_API_KEY
        value: "679155336334975"
      - key: CLOUDINARY_API_SECRET
        value: "SXnRD0bB-jEkyozdtmdAwcYBxxE"
