# Generated by Django 5.2.12 on 2026-03-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
