# Generated by Django 5.2.12 on 2026-03-22 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_category_image_url_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_the_box',
            field=models.CharField(blank=True, help_text='e.g. 1 SSD, Manual', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='Detailed specifications or specs JSON'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/gallery/')),
                ('image_url', models.URLField(blank=True, help_text='Alternative: External URL for gallery image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='api.product')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
