# Generated by Django 5.2.12 on 2026-03-27 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_otpverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_id', models.CharField(max_length=20, unique=True)),
                ('reason', models.CharField(choices=[('Changed Mind', 'Changed Mind'), ('Found Better Price', 'Found Better Price Elsewhere'), ('Delivery Delay', 'Delivery Taking Too Long'), ('Ordered By Mistake', 'Ordered By Mistake'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details about the cancellation')),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Refunded', 'Refunded'), ('Completed', 'Completed')], default='Requested', max_length=20)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_method', models.CharField(choices=[('Wallet', 'Wallet'), ('Original', 'Original Payment Method')], default='Wallet', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes for internal use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='api.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='api.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cancellations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(max_length=20, unique=True)),
                ('reason', models.CharField(choices=[('Defective', 'Defective/Damaged Product'), ('Wrong Item', 'Wrong Item Received'), ('Not As Described', 'Not As Described'), ('Size Issue', 'Size/Fit Issue'), ('Changed Mind', 'Changed Mind'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details about the return')),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pickup Scheduled', 'Pickup Scheduled'), ('Picked Up', 'Picked Up'), ('Refunded', 'Refunded'), ('Completed', 'Completed')], default='Requested', max_length=20)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_method', models.CharField(choices=[('Wallet', 'Wallet'), ('Original', 'Original Payment Method')], default='Wallet', max_length=20)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_address', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes for internal use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='api.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='api.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
