# Generated by Django 5.2.12 on 2026-03-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_wholesaleapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/banners/'),
        ),
        migrations.AddField(
            model_name='category',
            name='banner_image_url',
            field=models.URLField(blank=True, help_text='Alternative: Use external banner image URL'),
        ),
    ]
